version: "3.3"

services:
    mysql:
        image: vsamov/mysql-5.1.73
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: v1
            MYSQL_USER: v1
            MYSQL_PASSWORD: v1
        volumes:
            - "/var/lib/mysql"
    elasticsearch:
        build:
            context: ./
            dockerfile: ./docker/elasticsearch/Dockerfile
        ports:
            - "9200:9200"
            - "9300:9300"
    postgres:
        image: postgres:9.6
        restart: always
        environment:
            POSTGRES_USER: cfgov
            POSTGRES_PASSWORD: cfgov
    python:
        build: .
        ports:
            - "8000:8000"
        environment:
            MYSQL_ROOT_PW: root
            MYSQL_HOST: mysql
            MYSQL_NAME: v1
            MYSQL_USER: v1
            MYSQL_PW: v1
            ES_HOST: elasticsearch
            PG_DATABASE_URL: postgres://cfgov:cfgov@postgres/cfgov
        volumes:
            - ./:/src/cfgov-refresh
            - ./develop-apps:/src/develop-apps
        entrypoint:
            - sh
            - /src/cfgov-refresh/cfgov/entrypoint.sh
        depends_on:
            - mysql
            - elasticsearch
            - postgres
        working_dir: /src/cfgov-refresh
        env_file: .python_env
        stdin_open: true
        tty: true
